### ISSUE TITLE
mode: jit in tailwindcss builds a non-working CSS

### ISSUE THREAD

**Issue by edwintorok** [tmattio/spin-dream#1]
The default css generated by this template is missing a lot of the CSS actually used in the example, eg all the `lg:*` rules, and you get a page with a line of text and a giant arrow, which leaves the impression this is an unfinished project :![Screenshot from 2021-05-13 21-09-07](https://user-images.githubusercontent.com/721894/118181410-a46cfa00-b42f-11eb-9d93-e3200ad92cd4.png)

Instead of mode=jit using `NODE_ENV=production` has the same problem. It generates a different CSS but still just the giant arrow.
If I remove both mode=jit and do not use NODE_ENV=production I get a working css with a reasonable looking page but a giant 3.61 MB css:
![Screenshot from 2021-05-13 21-09-24](https://user-images.githubusercontent.com/721894/118181408-a3d46380-b42f-11eb-8882-9de16406c00e.png)

I'm not an expert on tailwind.css, but the configuration is probably wrong in some way if it drops stuff that is actually used (or maybe because it can't see the html file it doesn't know...)

**Comment by tmattio** [comment]
Thanks for the report, the problem was caused by a wrong value for the purge paths. This is fixed 🙂
