### ISSUE TITLE
Add screenshot to README, or post output somewhere

### ISSUE THREAD

**Issue by aantron** [tmattio/spin-dream#5]
For users to get a better idea of what they will get before they run commands or have to do anything, could you post screenshots and/or create a repo with the output? Would it be too much to ask to host the output somewhere?

Another very useful thing would be to include the actual usage instructions in the README, so that people can tell what the workflow will be like once setup is complete, without having to actually try the setup itself only to try to find that out (or worse, read any scripts or code).

**Comment by aantron** [comment]
Most importantly, how will live reload work?

**Comment by aantron** [comment]
It would also be very helpful to have Turbolinks, Tailwind, etc., be hyperlinked to their websites or the best pages presenting them. For example, I might already be familiar with Tailwind, but not Turbolinks, and it would be very helpful to very quickly find out if it's something I want to try or not. Same with Inter font.

**Comment by aantron** [comment]
Also suggest hyperlinking Spin itself :)

**Comment by tmattio** [comment]
Thanks a lot for the suggestions @aantron!

I've added a number of improvements to the README that I think cover the points you suggested:

- A screenshot of the server index page
- Links to Spin and Dream, and all of the (optional) dependencies
- Requirement sections with some instructions
- Example of a generated project that is linked from the README
- README in the generated projects that explain the development workflow, including the live reloading workflow

Let me know if you have any other suggestions 🙂

**Comment by aantron** [comment]
Thanks! I opened #8 for what's left.
