### ISSUE TITLE
Extra leading space before the template name

### ISSUE THREAD

**Issue by aantron** [tmattio/spin-dream#6]
![Снимок](https://user-images.githubusercontent.com/12073668/123788946-4912a080-d8e5-11eb-8c78-6535ac07fa4c.PNG)

I'm not sure if this is due to the template or due to Spin.

**Comment by tmattio** [comment]
Thanks, this is fixed in https://github.com/tmattio/spin/commit/6c939b892b2eb717964aa1ceeaf4df6cc6a7720d
